### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by ramereth**
Update to modern practices and do some cleanup as well.

### CODE REVIEW

**Comment by ramereth** [comment]
@osuosl-cookbooks/chefs please review

**Comment by armiller** [comment]
@ramereth are you still working on the tests? I get about 10 failures

**Comment by ramereth** [comment]
@armiller what failures are you seeing? I'm seeing none.

**Comment by ramereth** [comment]
Confirmed that this is happening due to the older version of chefdk on the workstations. I recommend we upgrade to version 0.14.25 which includes the same version of chef we run on the prod environment. Can you please verify this works properly with the newer version of chefdk?

**Comment by armiller** [comment]
👍

**Comment by ramereth** [comment]
!bump major

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a major-level version bump to v1.0.0.  Have a nice day!

**Pull request merged**
