### PR TITLE
Only create the recipe file if it doesn't exist

### PR DESCRIPTION
**Pull request by ramereth**
Don't overwrite an existing recipe.

@osuosl-cookbooks/chefs please review

### CODE REVIEW

**Comment by armiller** [comment]
:+1:

**Comment by fahlmant** [comment]
+1

**Comment by ramereth** [comment]
!bump patch

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.0.1.  Have a nice day!

**Pull request merged**
