### PR TITLE
Pass in chef_run instead of block

### PR DESCRIPTION
**Pull request by armiller**
This provides better error output for debugging

### CODE REVIEW

**Comment by armiller** [comment]
@osuosl-cookbooks/chefs

**Comment by ramereth** [comment]
:+1:

**Comment by armiller** [comment]
!bump patch

**Comment by osuosl-manatee** [comment]
Jenkins has merged this PR into `master` and has automatically performed a patch-level version bump to v1.0.2.  Have a nice day!

**Pull request merged**
